version: "3.9"

services:
  slam:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: slam
    environment:
      - CONFIG_FILE_URL=${CONFIG_FILE_URL}
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always
